
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package backend;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int APPCLO = 32;
  public static final int GE = 13;
  public static final int prec_app = 37;
  public static final int FDIV = 23;
  public static final int LPAREN = 6;
  public static final int INT = 3;
  public static final int prec_unary_minus = 36;
  public static final int FMUL = 22;
  public static final int RPAREN = 7;
  public static final int FADD = 25;
  public static final int NOP = 31;
  public static final int IN = 18;
  public static final int BOOL = 2;
  public static final int FLE = 12;
  public static final int CALL = 29;
  public static final int prec_let = 34;
  public static final int PLUS = 8;
  public static final int ASSIGN = 26;
  public static final int FNEG = 20;
  public static final int IF = 14;
  public static final int LE = 11;
  public static final int EOF = 0;
  public static final int EQUAL = 9;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int ADD = 27;
  public static final int IDENT = 5;
  public static final int FEQUAL = 10;
  public static final int FSUB = 24;
  public static final int NEG = 19;
  public static final int ELSE = 16;
  public static final int MEM = 21;
  public static final int prec_if = 35;
  public static final int LET = 17;
  public static final int FLOAT = 4;
  public static final int THEN = 15;
  public static final int UNDERSC = 33;
  public static final int SUB = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "INT",
  "FLOAT",
  "IDENT",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "EQUAL",
  "FEQUAL",
  "LE",
  "FLE",
  "GE",
  "IF",
  "THEN",
  "ELSE",
  "LET",
  "IN",
  "NEG",
  "FNEG",
  "MEM",
  "FMUL",
  "FDIV",
  "FSUB",
  "FADD",
  "ASSIGN",
  "ADD",
  "SUB",
  "CALL",
  "NEW",
  "NOP",
  "APPCLO",
  "UNDERSC",
  "prec_let",
  "prec_if",
  "prec_unary_minus",
  "prec_app"
  };

  /* non terminals */
  static final int toplevel = 5;
  static final int formal_args = 3;
  static final int ident_or_imm = 0;
  static final int fundefs = 4;
  static final int exp = 1;
  static final int asmt = 2;
}

